services:

    # Contao content element Jts22\ContaoAthleteProfileBundle\Controller\ContentElement\AthleteProfileListElementController
    Jts22\ContaoAthleteProfileBundle\Controller\ContentElement\AthleteProfileListElementController:
        tags:
            - { name: contao.content_element, category: texts, template: ce_athlete_profile_list_element }
            - { name: container.service_subscriber }
        public: true
    Jts22\ContaoAthleteProfileBundle\Controller\ContentElement\AthleteHonorListElementController:
        tags:
            - { name: contao.content_element, category: texts, template: ce_athlete_honor_list_element }
            - { name: container.service_subscriber }
        public: true




